### ISSUE TITLE
Automate census data downloads

### ISSUE THREAD

**Issue by virgesmith** [CatchDat/MSMCity#2]
Write an R package that uses http://www.nomisweb.co.uk query API to download census data

**Comment by virgesmith** [comment]
NomiswebApi.R is first cut of this. Currently has 3 functions:
getMetadata - input a census table name (e.g. DC1117EW) and it will return the table code in the API plus details of what data is in the table.
getODData - returns data from OD type tables
getEconData - returns data from tables with economic activity data.

If time permits query builder and output builder functions to generate specific request data would enable a single generic getData function that could be used on any table. This could form the basis of an R package.

**Comment by Robinlovelace** [comment]
Any progress with this? We should document this in the vignette. Will check the paper first though.
